services:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=transcriber
      - POSTGRES_USER=transcriber
      - POSTGRES_DB=transcriber
