version: '3.8'

services:
  web:
    build: .
    command: gunicorn --config gunicorn_config.py service:app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  celery_worker:
    build: .
    command: celery -A service.celery worker --loglevel=info
    depends_on:
      - redis
    networks:
      - app-network

  celery_beat:
    build: .
    command: celery -A service.celery beat --loglevel=info
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
