[tool.poetry]
name = "transcribe-service"
version = "0.1.0"
description = ""
authors = ["AryamaanScaler <aryamaan.jain@scaler.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
urllib3 = "^1.26.0"
psycopg2-binary = "^2.9.10"
psycopg2 = "^2.9.10"
pycurl = "^7.45.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
