"""added webhook url and payload

Revision ID: 6616b179d357
Revises: ef5c5b8d02e3
Create Date: 2025-01-08 18:54:04.267341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6616b179d357'
down_revision = 'ef5c5b8d02e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('payload', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('payload')
        batch_op.drop_column('webhook_url')

    # ### end Alembic commands ###
